table FactEVM
	lineageTag: 18b0b08d-8dba-47aa-b70a-2f0b1e5b3ed7

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 736216fe-b914-46f5-be29-b4d27497056f
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Planned_Value_PV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: d070badc-adc0-42fc-8ec3-5897f68fa10e
		summarizeBy: sum
		sourceColumn: Planned_Value_PV_MNOK

		annotation SummarizationSetBy = Automatic

	column Earned_Value_EV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: d2109933-23b5-4495-9a4b-31f13955018a
		summarizeBy: sum
		sourceColumn: Earned_Value_EV_MNOK

		annotation SummarizationSetBy = Automatic

	column Actual_Cost_AC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 7425fb28-c2d2-42e5-9b4d-1b231b99db22
		summarizeBy: sum
		sourceColumn: Actual_Cost_AC_MNOK

		annotation SummarizationSetBy = Automatic

	column Budget_At_Completion_BAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 8174b3c3-064e-4f5f-86be-e732d3f037c5
		summarizeBy: sum
		sourceColumn: Budget_At_Completion_BAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_At_Completion_EAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 142bce0b-f13a-4560-8af0-1beca3d7d63d
		summarizeBy: sum
		sourceColumn: Estimate_At_Completion_EAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_To_Complete_ETC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 09c5d240-1a08-4665-93b8-2e127570c570
		summarizeBy: sum
		sourceColumn: Estimate_To_Complete_ETC_MNOK

		annotation SummarizationSetBy = Automatic

	column Cost_Performance_Index_CPI
		dataType: double
		formatString: 0.00
		lineageTag: 2c232d88-2d79-41b2-a561-0912223a3dcf
		summarizeBy: average
		sourceColumn: Cost_Performance_Index_CPI

		annotation SummarizationSetBy = Automatic

	column Schedule_Performance_Index_SPI
		dataType: double
		formatString: 0.00
		lineageTag: a288a92e-bcf8-4987-8639-a944fd78811f
		summarizeBy: average
		sourceColumn: Schedule_Performance_Index_SPI

		annotation SummarizationSetBy = Automatic

	column Variance_At_Completion_VAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 518123ce-24d0-4ed2-ac17-8e6cf6949edb
		summarizeBy: sum
		sourceColumn: Variance_At_Completion_VAC_MNOK

		annotation SummarizationSetBy = Automatic

	partition FactEVM = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\FactEVM.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Planned_Value_PV_MNOK", type number}, {"Earned_Value_EV_MNOK", type number}, {"Actual_Cost_AC_MNOK", type number}, {"Budget_At_Completion_BAC_MNOK", type number}, {"Estimate_At_Completion_EAC_MNOK", type number}, {"Estimate_To_Complete_ETC_MNOK", type number}, {"Cost_Performance_Index_CPI", type number}, {"Schedule_Performance_Index_SPI", type number}, {"Variance_At_Completion_VAC_MNOK", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

