table DimAccountHierarchy
	lineageTag: 22287e34-c1ef-4bbe-a924-0f4365dace2b

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: a4265f30-b89d-4e54-b1a7-e9b2be7147c4
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: f00794bf-ab38-4bea-a719-df79bea5006d
		summarizeBy: none
		sourceColumn: Kontonavn

		annotation SummarizationSetBy = Automatic

	column Nivaa1_Navn
		dataType: string
		lineageTag: 39767dbe-22cb-4aaa-80e4-cb8c8c1d15c8
		summarizeBy: none
		sourceColumn: Nivaa1_Navn

		annotation SummarizationSetBy = Automatic

	column Kontotype
		dataType: string
		lineageTag: 89a69432-f5dd-4408-92a4-12e3ed3e091d
		summarizeBy: none
		sourceColumn: Kontotype

		annotation SummarizationSetBy = Automatic

	column SRS_regnskapslinje
		dataType: string
		lineageTag: a5952566-16cf-4f33-87d8-2776c5d3a104
		summarizeBy: none
		sourceColumn: SRS_regnskapslinje

		annotation SummarizationSetBy = Automatic

	partition DimAccountHierarchy = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\DimAccountHierarchy.csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Konto", Int64.Type}, {"Kontonavn", type text}, {"Nivaa1_Navn", type text}, {"Kontotype", type text}, {"SRS_regnskapslinje", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

