table DimDate_2027
	lineageTag: 1000d20a-ac8e-44d5-936e-90d3c7d350c2
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 46885708-3c07-4ff2-9075-4bfb51009559
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: ed5e647b-433e-46ac-a1f1-3e3f50e3d3c4
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 8e6b2f98-1b05-45e3-aa79-71a5f42a0da0
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: 386805bf-a728-4a9e-b268-bbb8788f4bd9
		summarizeBy: none
		sourceColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		lineageTag: 4bc900ae-20ef-4122-b492-1beaca705480
		summarizeBy: none
		sourceColumn: MaanedNavn
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavnKort
		dataType: string
		lineageTag: 318afea5-13f6-4c12-b254-d208efe14ffa
		summarizeBy: none
		sourceColumn: MaanedNavnKort
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: 59531ad4-579c-4f13-a27e-498ede290df3
		summarizeBy: none
		sourceColumn: Kvartal

		annotation SummarizationSetBy = Automatic

	column ErActualYTD
		dataType: boolean
		lineageTag: ea035d0b-6ec7-459f-9016-f29b2b35be0b
		summarizeBy: none
		sourceColumn: ErActualYTD

		annotation SummarizationSetBy = Automatic

	column Budsjettaar
		dataType: int64
		formatString: 0
		lineageTag: 59dfc98d-433c-4263-bccc-c0ea850c9d09
		summarizeBy: none
		sourceColumn: Budsjettaar

		annotation SummarizationSetBy = Automatic

	partition DimDate_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\DimDate_2027.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Dato", type date}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavn", type text}, {"MaanedNavnKort", type text}, {"Kvartal", type text}, {"ErActualYTD", type logical}, {"Budsjettaar", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

