table DimDate
	lineageTag: 71a81ca8-9e8d-4e2b-9a1f-6d67afe84d68
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: bb12ddb5-3258-4dba-a900-4c61e735b346
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: dfc8b2a8-1dc5-4059-9f61-8d37a7b5f225
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 16aa27b9-4d76-4cef-86d6-e46178ce17d8
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: 3506aea3-73e3-42b5-bdac-140ca39f94ae
		summarizeBy: none
		sourceColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		lineageTag: c38b2e37-1f07-45c8-8f43-4dc352d4d524
		summarizeBy: none
		sourceColumn: MaanedNavn
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavnKort
		dataType: string
		lineageTag: 3e601519-eb14-41ef-ad5c-b95a43707a35
		summarizeBy: none
		sourceColumn: MaanedNavnKort
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: e884d8d1-3c6d-41d8-bdbc-ca7762f148c6
		summarizeBy: none
		sourceColumn: Kvartal

		annotation SummarizationSetBy = Automatic

	column ErActualYTD
		dataType: boolean
		lineageTag: 2ad6b713-9781-41bc-92c3-019e8ccd0ce8
		summarizeBy: none
		sourceColumn: ErActualYTD

		annotation SummarizationSetBy = Automatic

	column PeriodeBeskrivelse
		dataType: string
		lineageTag: 0ef50e94-eead-4a30-86ff-1d1ca29111db
		summarizeBy: none
		sourceColumn: PeriodeBeskrivelse

		annotation SummarizationSetBy = Automatic

	column PeriodeType
		dataType: string
		lineageTag: 5c81ddf7-7351-4556-b83f-4c4f07abc8e2
		summarizeBy: none
		sourceColumn: PeriodeType

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\DimDate.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavn", type text}, {"MaanedNavnKort", type text}, {"Kvartal", type text}, {"ErActualYTD", type logical}, {"PeriodeBeskrivelse", type text}}),
				    #"Added Dato" = Table.AddColumn(#"Changed Type", "Dato", each #date([Aar], [MaanedNummer], 1), type date),
				    #"Added PeriodeType" = Table.AddColumn(#"Added Dato", "PeriodeType", each [PeriodeBeskrivelse], type text)
				in
				    #"Added PeriodeType"

	annotation PBI_ResultType = Table

