table DimForecastVersion
	lineageTag: 4557a2ca-04ac-42ee-98b9-44a425593dee

	column VersjonKode
		dataType: string
		lineageTag: 3822a453-b61e-40b5-987a-6f013280de91
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column VersjonNavn
		dataType: string
		lineageTag: 98bb8b90-d38a-4041-a06b-90e7906407e1
		summarizeBy: none
		sourceColumn: VersjonNavn

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: b3975d51-75d2-4455-a284-3cd94afa44b9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SisteOppdatert
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 8e2d38ab-1527-4901-9d7d-846213d48ed1
		summarizeBy: none
		sourceColumn: SisteOppdatert

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimForecastVersion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\DimForecastVersion.csv"),[Delimiter=";", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"VersjonKode", type text}, {"VersjonNavn", type text}, {"Status", type text}, {"SisteOppdatert", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

