table DimOrganization
	lineageTag: b211751d-e265-4f17-9c9d-49ef1e82c36e

	column OrgKode
		dataType: string
		lineageTag: 22fc635a-328e-41d9-a484-6be442b700ec
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Enhetsnavn
		dataType: string
		lineageTag: b7fb90e8-821d-42c6-beab-336ecdf66b26
		summarizeBy: none
		sourceColumn: Enhetsnavn

		annotation SummarizationSetBy = Automatic

	column Nivaa1
		dataType: string
		lineageTag: ec232711-58b2-4587-9e81-756094583d8b
		summarizeBy: none
		sourceColumn: Nivaa1

		annotation SummarizationSetBy = Automatic

	column Nivaa2
		dataType: string
		lineageTag: 4a5f401f-afee-4821-b22e-e73a7cd39a40
		summarizeBy: none
		sourceColumn: Nivaa2

		annotation SummarizationSetBy = Automatic

	column Nivaa3
		dataType: string
		lineageTag: 3ac2be17-f869-465a-99f8-67b5bdc9ebd1
		summarizeBy: none
		sourceColumn: Nivaa3

		annotation SummarizationSetBy = Automatic

	column Budsjettansvarlig
		dataType: string
		lineageTag: 7fcab01c-f99d-4e21-ae56-d3acae99733d
		summarizeBy: none
		sourceColumn: Budsjettansvarlig

		annotation SummarizationSetBy = Automatic

	column LederTittel
		dataType: string
		lineageTag: 484c6851-254b-45ff-8360-0ad28a8cc6a8
		summarizeBy: none
		sourceColumn: LederTittel

		annotation SummarizationSetBy = Automatic

	column Virksomhetstype
		dataType: string
		lineageTag: e1b64c80-d2e5-4575-8309-eb55e1b43b2e
		summarizeBy: none
		sourceColumn: Virksomhetstype

		annotation SummarizationSetBy = Automatic

	column Fakultetsnavn
		dataType: string
		lineageTag: ee3991b9-2eb8-449a-b101-e4abcd54a120
		summarizeBy: none
		sourceColumn: Fakultetsnavn

		annotation SummarizationSetBy = Automatic

	partition DimOrganization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\DimOrganization.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", type text}, {"Enhetsnavn", type text}, {"Nivaa1", type text}, {"Nivaa2", type text}, {"Nivaa3", type text}, {"Budsjettansvarlig", type text}, {"LederTittel", type text}, {"Virksomhetstype", type text}}),
				    #"Added Fakultetsnavn" = Table.AddColumn(#"Changed Type", "Fakultetsnavn", each [Nivaa2], type text)
				in
				    #"Added Fakultetsnavn"

	annotation PBI_ResultType = Table

