table FactStudents_2027
	lineageTag: d2b12a7e-05d2-460b-95d8-0b974d25b14b

	column StudentNokkel
		dataType: string
		lineageTag: be41efef-e837-4d0a-a612-d7388fecae42
		summarizeBy: none
		sourceColumn: StudentNokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: d5cbc395-5b79-44b6-a190-50d3ec0755aa
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: b0d4e35a-8b44-48a0-9663-0b592c3664ba
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Studieprogram
		dataType: string
		lineageTag: 0c8e5ec9-c5fd-4a41-8d62-e2596299fb91
		summarizeBy: none
		sourceColumn: Studieprogram

		annotation SummarizationSetBy = Automatic

	column RegistrerteStudenter
		dataType: int64
		formatString: #,##0
		lineageTag: 0a2e541a-31dc-4867-943d-3b25c9eb87e8
		summarizeBy: sum
		sourceColumn: RegistrerteStudenter

		annotation SummarizationSetBy = Automatic

	column SPE60_Baseline_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: ec24c04c-d7ad-4fbd-936c-c9db9de3db8e
		summarizeBy: sum
		sourceColumn: SPE60_Baseline_2025

		annotation SummarizationSetBy = Automatic

	column SPE60_Vekst_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: a8fe8c7a-2f9a-4122-a002-7ea3e73fe1b7
		summarizeBy: sum
		sourceColumn: SPE60_Vekst_2025

		annotation SummarizationSetBy = Automatic

	column SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: b2e358af-c18d-4a25-932b-ba5bf04b9d8e
		summarizeBy: sum
		sourceColumn: SPE60

		annotation SummarizationSetBy = Automatic

	column KDKategori
		dataType: string
		lineageTag: c71a7c0c-83cf-47b6-9380-0560486b7697
		summarizeBy: none
		sourceColumn: KDKategori

		annotation SummarizationSetBy = Automatic

	column KDSats_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 08407a56-3afb-4a16-b088-f786e7b8d6b2
		summarizeBy: sum
		sourceColumn: KDSats_NOK

		annotation SummarizationSetBy = Automatic

	column KD_Marginal_Inntekt_2027
		dataType: double
		formatString: #,##0
		lineageTag: 574115df-120a-41d4-9b34-59a08e0648a9
		summarizeBy: sum
		sourceColumn: KD_Marginal_Inntekt_2027

		annotation SummarizationSetBy = Automatic

	column Studenter_pr_UF
		dataType: double
		formatString: 0.0
		lineageTag: 3dfbc2e5-0434-4c29-bac3-51a0de01bf2d
		summarizeBy: average
		sourceColumn: Studenter_pr_UF

		annotation SummarizationSetBy = Automatic

	column StudenterPrUF
		dataType: double
		formatString: 0.0
		lineageTag: 92cce759-7266-4d66-9792-ebb72f934d36
		summarizeBy: average
		sourceColumn: StudenterPrUF

		annotation SummarizationSetBy = Automatic

	partition FactStudents_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactStudents_2027.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StudentNokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Studieprogram", type text}, {"RegistrerteStudenter", Int64.Type}, {"SPE60_Baseline_2025", type number}, {"SPE60_Vekst_2025", type number}, {"SPE60", type number}, {"KDKategori", type text}, {"KDSats_NOK", type number}, {"KD_Marginal_Inntekt_2027", type number}, {"Studenter_pr_UF", type number}}),
				    #"Added StudenterPrUF" = Table.AddColumn(#"Changed Type", "StudenterPrUF", each [Studenter_pr_UF], type number)
				in
				    #"Added StudenterPrUF"

	annotation PBI_ResultType = Table

