table FactGL
	lineageTag: 64d51590-bc89-4aa3-98cf-e3e45a6e1c05

	column TransaksjonID
		dataType: string
		lineageTag: 2748478e-fac2-4f16-a2c4-ceb4254f7562
		summarizeBy: none
		sourceColumn: TransaksjonID

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: b42adb85-f1e3-4b90-a55f-37d574d0d61e
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: fd321928-9314-4b64-a45b-0e6b644739e0
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: b2d21614-becf-409a-b96e-897167620df1
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column Bokforingstype
		dataType: string
		lineageTag: 20aa6b61-42be-4b2e-83df-d28dbd3042b1
		summarizeBy: none
		sourceColumn: Bokforingstype

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: d0afd741-f77f-469e-bbf4-74e0d4f78ccb
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column Belop_signert
		dataType: double
		formatString: #,##0
		lineageTag: da6e38c4-38f7-4af2-bd34-ce11fa820253
		summarizeBy: sum
		sourceColumn: Belop_signert

		annotation SummarizationSetBy = Automatic

	column Budsjettansvarsområde
		dataType: string
		lineageTag: f4ad8083-4e93-4d15-b73f-4e36bc473010
		summarizeBy: none
		sourceColumn: Budsjettansvarsområde

		annotation SummarizationSetBy = Automatic

	column BudsjettansvarligLeder
		dataType: string
		lineageTag: f814c685-7bf8-4c30-9a31-eb58dc346c6e
		summarizeBy: none
		sourceColumn: BudsjettansvarligLeder

		annotation SummarizationSetBy = Automatic

	column ProsjektID
		dataType: string
		lineageTag: e4613518-50ff-4c2a-b221-d0cc7f64ecb4
		summarizeBy: none
		sourceColumn: ProsjektID

		annotation SummarizationSetBy = Automatic

	column Avvikstype_Beskrivelse
		dataType: string
		lineageTag: 2dfdb21d-2dac-400a-b53d-392c298e997e
		summarizeBy: none
		sourceColumn: Avvikstype_Beskrivelse

		annotation SummarizationSetBy = Automatic

	partition FactGL = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactGL.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TransaksjonID", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Konto", Int64.Type}, {"Bokforingstype", type text}, {"VersjonKode", type text}, {"Belop_signert", type number}, {"Budsjettansvarsområde", type text}, {"BudsjettansvarligLeder", type text}, {"ProsjektID", type text}, {"Avvikstype_Beskrivelse", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

