table FactForecastMethod
	lineageTag: 444cf673-5718-4f0f-936f-ca08b7839125

	column Prio
		dataType: string
		lineageTag: 3f1668e9-82d7-4ff4-b411-8bafd8f92edf
		summarizeBy: none
		sourceColumn: Prio

		annotation SummarizationSetBy = Automatic

	column Budsjettpost
		dataType: string
		lineageTag: b659d975-db2f-4877-b8eb-80cec9345ab7
		summarizeBy: none
		sourceColumn: Budsjettpost

		annotation SummarizationSetBy = Automatic

	column KontoTabell
		dataType: string
		lineageTag: 3055f4e3-2de8-4fa3-9d7f-a0feea9546af
		summarizeBy: none
		sourceColumn: KontoTabell

		annotation SummarizationSetBy = Automatic

	column Baseline2027
		dataType: double
		formatString: #,##0
		lineageTag: 80445bf4-9a48-41a9-9496-fda5ff31e3d9
		summarizeBy: sum
		sourceColumn: Baseline2027

		annotation SummarizationSetBy = Automatic

	column Prognosemetode
		dataType: string
		lineageTag: 4f8cc026-f026-41b3-b412-055d368657e2
		summarizeBy: none
		sourceColumn: Prognosemetode

		annotation SummarizationSetBy = Automatic

	column DriverInput
		dataType: string
		lineageTag: be41fa5a-330e-49c7-a3a3-ddfb37a56088
		summarizeBy: none
		sourceColumn: DriverInput

		annotation SummarizationSetBy = Automatic

	column OperativBeregning
		dataType: string
		lineageTag: 6351ed18-65ff-4c07-8837-c0f6e107133f
		summarizeBy: none
		sourceColumn: OperativBeregning

		annotation SummarizationSetBy = Automatic

	column Oppdateringsfrekvens
		dataType: string
		lineageTag: 78fcc262-70e8-4e3a-8847-db0f2b7c0c1f
		summarizeBy: none
		sourceColumn: Oppdateringsfrekvens

		annotation SummarizationSetBy = Automatic

	partition FactForecastMethod = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactForecastMethod.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Prio", type text}, {"Budsjettpost", type text}, {"KontoTabell", type text}, {"Baseline2027", type number}, {"Prognosemetode", type text}, {"DriverInput", type text}, {"OperativBeregning", type text}, {"Oppdateringsfrekvens", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

