table FactFTE_2027
	lineageTag: 3daa6d92-69ee-420f-b09f-c9b6c0446585

	column FTENokkel
		dataType: string
		lineageTag: 0d69b521-37b1-4e85-864f-5ae6e76099af
		summarizeBy: none
		sourceColumn: FTENokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: ddfe0e97-97cc-4cf0-9773-bc99b9f4492b
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: 2367b0d7-7f2e-4d21-8962-ce53847b1056
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Budsjettert_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: 5d4c8d5a-e3b8-4dd6-a059-011238faa398
		summarizeBy: sum
		sourceColumn: Budsjettert_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Vakans_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: deb3e4e1-fe41-4e0f-903b-8da7369cd520
		summarizeBy: sum
		sourceColumn: Vakans_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Aarsverk_Totalt
		dataType: double
		formatString: #,##0.0
		lineageTag: cbedd9fc-2737-45cc-8720-067109a5ff4d
		summarizeBy: sum
		sourceColumn: Aarsverk_Totalt

		annotation SummarizationSetBy = Automatic

	column Aarsverk_UF
		dataType: double
		formatString: #,##0.0
		lineageTag: b8165e53-3cd3-43af-bf41-ccdb2e2bfd3f
		summarizeBy: sum
		sourceColumn: Aarsverk_UF

		annotation SummarizationSetBy = Automatic

	column Aarsverk_TA
		dataType: double
		formatString: #,##0.0
		lineageTag: ba8b11ea-f0ee-42e3-956d-2b2cce399f02
		summarizeBy: sum
		sourceColumn: Aarsverk_TA

		annotation SummarizationSetBy = Automatic

	column Antall_Ansatte
		dataType: int64
		formatString: 0
		lineageTag: bd7d4794-2dfd-481c-9a78-099df2b2c159
		summarizeBy: sum
		sourceColumn: Antall_Ansatte

		annotation SummarizationSetBy = Automatic

	column Maanedlig_Lonnskostnad
		dataType: double
		formatString: #,##0
		lineageTag: 3cbc6844-3ce8-400b-aa8f-366517477964
		summarizeBy: sum
		sourceColumn: Maanedlig_Lonnskostnad

		annotation SummarizationSetBy = Automatic

	column Lennsandel_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: 7976cfb3-0e19-46a9-99b1-ac66ad2b7c5e
		summarizeBy: average
		sourceColumn: Lennsandel_Pct

		annotation SummarizationSetBy = Automatic

	partition FactFTE_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactFTE_2027.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"FTENokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Budsjettert_Aarsverk", type number}, {"Vakans_Aarsverk", type number}, {"Aarsverk_Totalt", type number}, {"Aarsverk_UF", type number}, {"Aarsverk_TA", type number}, {"Antall_Ansatte", Int64.Type}, {"Maanedlig_Lonnskostnad", type number}, {"Lennsandel_Pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

