table FactBudget
	lineageTag: 3098a097-b256-4fdd-81d5-db677b05346a

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 7d4e9b2a-8ae1-4270-b849-d16ddaa71205
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: 289078e8-7d7e-40db-ab2b-8d943ef805c2
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: ba4161fc-ee57-4e97-a17d-e4f8f5a97805
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: a2dfecae-df1e-4f5e-b11e-9f7d24a2d649
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column BudsjettBelop
		dataType: double
		formatString: #,##0
		lineageTag: a283d60e-62d5-4c4c-aa07-1a130a1a7324
		summarizeBy: sum
		sourceColumn: BudsjettBelop

		annotation SummarizationSetBy = Automatic

	column Budsjettansvarsområde
		dataType: string
		lineageTag: 9c10dd03-ceb5-4a4e-8fac-20564b3ca89a
		summarizeBy: none
		sourceColumn: Budsjettansvarsområde

		annotation SummarizationSetBy = Automatic

	column BudsjettansvarligLeder
		dataType: string
		lineageTag: 2e43e4c8-0540-4367-8e6e-e1ca423d7f03
		summarizeBy: none
		sourceColumn: BudsjettansvarligLeder

		annotation SummarizationSetBy = Automatic

	partition FactBudget = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactBudget.csv"),[Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Konto", Int64.Type}, {"VersjonKode", type text}, {"BudsjettBelop", type number}, {"Budsjettansvarsområde", type text}, {"BudsjettansvarligLeder", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

