table FactEVM
	lineageTag: 32f0faf8-12ba-41de-920b-3754418806e0

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 17d4d3f4-1fb6-40a4-8293-bfc0afc88e3c
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column BAC_BudgetAtCompletion
		dataType: double
		formatString: #,##0
		lineageTag: ebbf66c4-c7c1-409a-97c3-8b8d3d862d63
		summarizeBy: sum
		sourceColumn: BAC_BudgetAtCompletion

		annotation SummarizationSetBy = Automatic

	column PlannedValue_PV
		dataType: double
		formatString: #,##0
		lineageTag: ce30bc7b-f474-480b-aa59-1dedace9f18e
		summarizeBy: sum
		sourceColumn: PlannedValue_PV

		annotation SummarizationSetBy = Automatic

	column EarnedValue_EV
		dataType: double
		formatString: #,##0
		lineageTag: f890a423-f3c6-4991-b687-d7208c693b85
		summarizeBy: sum
		sourceColumn: EarnedValue_EV

		annotation SummarizationSetBy = Automatic

	column ActualCost_AC
		dataType: double
		formatString: #,##0
		lineageTag: 587c472c-67b9-4f53-82c5-738c2475a155
		summarizeBy: sum
		sourceColumn: ActualCost_AC

		annotation SummarizationSetBy = Automatic

	column EstimateAtCompletion_EAC
		dataType: double
		formatString: #,##0
		lineageTag: 3e719de7-7b17-4639-9057-738f8c34d760
		summarizeBy: sum
		sourceColumn: EstimateAtCompletion_EAC

		annotation SummarizationSetBy = Automatic

	column EstimateToComplete_ETC
		dataType: double
		formatString: #,##0
		lineageTag: ce2c81e6-00e8-475a-809f-63fd40cdac03
		summarizeBy: sum
		sourceColumn: EstimateToComplete_ETC

		annotation SummarizationSetBy = Automatic

	column VarianceAtCompletion_VAC
		dataType: double
		formatString: #,##0
		lineageTag: 471f3df0-ddc6-44c9-9549-c7bfa390d302
		summarizeBy: sum
		sourceColumn: VarianceAtCompletion_VAC

		annotation SummarizationSetBy = Automatic

	column CostPerformanceIndex_CPI
		dataType: double
		formatString: 0.00
		lineageTag: a12a2f9b-9434-4aff-a512-eeb8869d6644
		summarizeBy: average
		sourceColumn: CostPerformanceIndex_CPI

		annotation SummarizationSetBy = Automatic

	column SchedulePerformanceIndex_SPI
		dataType: double
		formatString: 0.00
		lineageTag: 8aba59f4-b639-4b77-a205-5f80ae6f653d
		summarizeBy: average
		sourceColumn: SchedulePerformanceIndex_SPI

		annotation SummarizationSetBy = Automatic

	column Planned_Value_PV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 343f5a63-1aec-42e6-a9b6-3934b92386dc
		summarizeBy: sum
		sourceColumn: Planned_Value_PV_MNOK

		annotation SummarizationSetBy = Automatic

	column Earned_Value_EV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 7775c3a6-76ab-4dc2-b215-89a7a6a47f7a
		summarizeBy: sum
		sourceColumn: Earned_Value_EV_MNOK

		annotation SummarizationSetBy = Automatic

	column Actual_Cost_AC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 6753989a-b3f8-4bcf-b1cb-5db3ddcb4200
		summarizeBy: sum
		sourceColumn: Actual_Cost_AC_MNOK

		annotation SummarizationSetBy = Automatic

	column Budget_At_Completion_BAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 9aec8f8d-d8cd-42fd-8687-80ade0cfdb3e
		summarizeBy: sum
		sourceColumn: Budget_At_Completion_BAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_At_Completion_EAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 37e6b951-241b-428f-982b-77a1b01d737b
		summarizeBy: sum
		sourceColumn: Estimate_At_Completion_EAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_To_Complete_ETC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 5c229574-aa63-4b07-b152-4bb9bea9393b
		summarizeBy: sum
		sourceColumn: Estimate_To_Complete_ETC_MNOK

		annotation SummarizationSetBy = Automatic

	column Variance_At_Completion_VAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 1b1870a7-f924-4f56-a1b8-b57de241f324
		summarizeBy: sum
		sourceColumn: Variance_At_Completion_VAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Cost_Performance_Index_CPI
		dataType: double
		formatString: 0.00
		lineageTag: 23c5d22e-50f4-4eb8-800c-662e35e0136e
		summarizeBy: average
		sourceColumn: Cost_Performance_Index_CPI

		annotation SummarizationSetBy = Automatic

	column Schedule_Performance_Index_SPI
		dataType: double
		formatString: 0.00
		lineageTag: 977b9706-c1be-4e52-8414-0ebdf14f930e
		summarizeBy: average
		sourceColumn: Schedule_Performance_Index_SPI

		annotation SummarizationSetBy = Automatic

	partition FactEVM = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactEVM.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"BAC_BudgetAtCompletion", type number}, {"PlannedValue_PV", type number}, {"EarnedValue_EV", type number}, {"ActualCost_AC", type number}, {"EstimateAtCompletion_EAC", type number}, {"EstimateToComplete_ETC", type number}, {"VarianceAtCompletion_VAC", type number}, {"CostPerformanceIndex_CPI", type number}, {"SchedulePerformanceIndex_SPI", type number}}),
				    #"Added PV_MNOK" = Table.AddColumn(#"Changed Type", "Planned_Value_PV_MNOK", each [PlannedValue_PV] / 1000000, type number),
				    #"Added EV_MNOK" = Table.AddColumn(#"Added PV_MNOK", "Earned_Value_EV_MNOK", each [EarnedValue_EV] / 1000000, type number),
				    #"Added AC_MNOK" = Table.AddColumn(#"Added EV_MNOK", "Actual_Cost_AC_MNOK", each [ActualCost_AC] / 1000000, type number),
				    #"Added BAC_MNOK" = Table.AddColumn(#"Added AC_MNOK", "Budget_At_Completion_BAC_MNOK", each [BAC_BudgetAtCompletion] / 1000000, type number),
				    #"Added EAC_MNOK" = Table.AddColumn(#"Added BAC_MNOK", "Estimate_At_Completion_EAC_MNOK", each [EstimateAtCompletion_EAC] / 1000000, type number),
				    #"Added ETC_MNOK" = Table.AddColumn(#"Added EAC_MNOK", "Estimate_To_Complete_ETC_MNOK", each [EstimateToComplete_ETC] / 1000000, type number),
				    #"Added VAC_MNOK" = Table.AddColumn(#"Added ETC_MNOK", "Variance_At_Completion_VAC_MNOK", each [VarianceAtCompletion_VAC] / 1000000, type number),
				    #"Added CPI" = Table.AddColumn(#"Added VAC_MNOK", "Cost_Performance_Index_CPI", each [CostPerformanceIndex_CPI], type number),
				    #"Added SPI" = Table.AddColumn(#"Added CPI", "Schedule_Performance_Index_SPI", each [SchedulePerformanceIndex_SPI], type number)
				in
				    #"Added SPI"

	annotation PBI_ResultType = Table

