table FactAction
	lineageTag: a49fef89-7636-44cf-ae7e-f1a2fd76c7e3

	column TiltakID
		dataType: string
		lineageTag: 4d46f618-fcc4-4d49-a531-c1a810324d4b
		summarizeBy: none
		sourceColumn: TiltakID

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: aa759834-69e4-471a-abf0-775de84b035a
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Budsjettansvarsområde
		dataType: string
		lineageTag: b6227b90-b2e4-4967-a753-71575d2cbad5
		summarizeBy: none
		sourceColumn: Budsjettansvarsområde

		annotation SummarizationSetBy = Automatic

	column AnsvarligLeder
		dataType: string
		lineageTag: deafa96d-72f0-4397-a356-430162e4d5ec
		summarizeBy: none
		sourceColumn: AnsvarligLeder

		annotation SummarizationSetBy = Automatic

	column TiltakNavn
		dataType: string
		lineageTag: d4265d9f-f19d-4987-b358-4ecafaa3ad1b
		summarizeBy: none
		sourceColumn: TiltakNavn

		annotation SummarizationSetBy = Automatic

	column ForventetInnsparingNOK
		dataType: double
		formatString: #,##0
		lineageTag: f5f0d858-83a3-4082-8b98-160ba6aaf320
		summarizeBy: sum
		sourceColumn: ForventetInnsparingNOK

		annotation SummarizationSetBy = Automatic

	column RealisertInnsparingNOK
		dataType: double
		formatString: #,##0
		lineageTag: 0d84857a-fe80-4ca4-8c26-d3168626c554
		summarizeBy: sum
		sourceColumn: RealisertInnsparingNOK

		annotation SummarizationSetBy = Automatic

	column ForventetEffekt
		dataType: double
		formatString: #,##0
		lineageTag: dd3ab45c-101b-4514-8065-c49d915dd950
		summarizeBy: sum
		sourceColumn: ForventetEffekt

		annotation SummarizationSetBy = Automatic

	column RealisertEffekt
		dataType: double
		formatString: #,##0
		lineageTag: a2e6bdb6-3c8e-41d1-9a89-7b85412267ca
		summarizeBy: sum
		sourceColumn: RealisertEffekt

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 479c454b-faca-436d-9590-d51bba1a1e1b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column FristDato
		dataType: string
		lineageTag: 23eb68b3-2f72-4ecf-bc51-c65b82e17eb1
		summarizeBy: none
		sourceColumn: FristDato

		annotation SummarizationSetBy = Automatic

	partition FactAction = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactAction.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TiltakID", type text}, {"OrgKode", type text}, {"Budsjettansvarsområde", type text}, {"AnsvarligLeder", type text}, {"TiltakNavn", type text}, {"ForventetInnsparingNOK", type number}, {"RealisertInnsparingNOK", type number}, {"Status", type text}, {"FristDato", type text}}),
				    #"Added ForventetEffekt" = Table.AddColumn(#"Changed Type", "ForventetEffekt", each [ForventetInnsparingNOK], type number),
				    #"Added RealisertEffekt" = Table.AddColumn(#"Added ForventetEffekt", "RealisertEffekt", each [RealisertInnsparingNOK], type number)
				in
				    #"Added RealisertEffekt"

	annotation PBI_ResultType = Table

