table FactStudents
	lineageTag: 2dda70a9-566a-4b00-9e2c-9faa015ec460

	column StudentNokkel
		dataType: string
		lineageTag: 8328e2a4-8db7-4e8b-8191-292fcc815416
		summarizeBy: none
		sourceColumn: StudentNokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 32f1ca78-3161-4707-9bd1-c3c09a6f0b41
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: edb1d8e7-ffaf-4337-9c87-f6e6cb142642
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Studieprogram
		dataType: string
		lineageTag: 4ae39447-0f43-4b46-b455-ceb61619165b
		summarizeBy: none
		sourceColumn: Studieprogram

		annotation SummarizationSetBy = Automatic

	column RegistrerteStudenter
		dataType: int64
		formatString: #,##0
		lineageTag: ace02c1f-4982-48fa-be61-6b3ac8c2f083
		summarizeBy: sum
		sourceColumn: RegistrerteStudenter

		annotation SummarizationSetBy = Automatic

	column SPE60_Baseline_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: 221dd25f-60ef-4dd3-849b-6265b5231e18
		summarizeBy: sum
		sourceColumn: SPE60_Baseline_2025

		annotation SummarizationSetBy = Automatic

	column SPE60_Vekst_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: 16b8f2ca-8b28-416c-84fb-ae2b60fd433a
		summarizeBy: sum
		sourceColumn: SPE60_Vekst_2025

		annotation SummarizationSetBy = Automatic

	column SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: 795a7e79-c286-4025-8b0d-be6912432630
		summarizeBy: sum
		sourceColumn: SPE60

		annotation SummarizationSetBy = Automatic

	column KDKategori
		dataType: string
		lineageTag: 13ab35ed-73f0-4943-ac14-db49c7a07586
		summarizeBy: none
		sourceColumn: KDKategori

		annotation SummarizationSetBy = Automatic

	column KDSats_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 57acba12-fec6-4941-919b-fd585b89f47d
		summarizeBy: sum
		sourceColumn: KDSats_NOK

		annotation SummarizationSetBy = Automatic

	column KD_Marginal_Inntekt_2027
		dataType: double
		formatString: #,##0
		lineageTag: 8e66b01c-7aea-482f-a90a-a0926c9e68aa
		summarizeBy: sum
		sourceColumn: KD_Marginal_Inntekt_2027

		annotation SummarizationSetBy = Automatic

	column Studenter_pr_UF
		dataType: double
		formatString: 0.0
		lineageTag: 3eb346ec-b90a-44b6-9b9d-c4d58ff122e0
		summarizeBy: average
		sourceColumn: Studenter_pr_UF

		annotation SummarizationSetBy = Automatic

	column StudenterPrUF
		dataType: double
		formatString: 0.0
		lineageTag: b03c8598-9d72-457a-a999-3530e13f4d3f
		summarizeBy: average
		sourceColumn: StudenterPrUF

		annotation SummarizationSetBy = Automatic

	partition FactStudents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactStudents.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StudentNokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Studieprogram", type text}, {"RegistrerteStudenter", Int64.Type}, {"SPE60_Baseline_2025", type number}, {"SPE60_Vekst_2025", type number}, {"SPE60", type number}, {"KDKategori", type text}, {"KDSats_NOK", type number}, {"KD_Marginal_Inntekt_2027", type number}, {"Studenter_pr_UF", type number}}),
				    #"Added StudenterPrUF" = Table.AddColumn(#"Changed Type", "StudenterPrUF", each [Studenter_pr_UF], type number)
				in
				    #"Added StudenterPrUF"

	annotation PBI_ResultType = Table

