table FactStudents_2027
	lineageTag: 1a8ba17b-172a-41a2-a881-23bbd84d1c05

	column StudentNokkel
		dataType: string
		lineageTag: 5a094b28-71c2-4e40-8a99-54a549d6f85c
		summarizeBy: none
		sourceColumn: StudentNokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 831d5347-0d6a-4abb-be3c-7054deb84c98
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: 548a4490-042c-4d9a-96ad-1ad7b701b768
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Studieprogram
		dataType: string
		lineageTag: bcf68db1-9d5e-4558-8041-a143a2d8f943
		summarizeBy: none
		sourceColumn: Studieprogram

		annotation SummarizationSetBy = Automatic

	column RegistrerteStudenter
		dataType: int64
		formatString: #,##0
		lineageTag: 1a19eb13-0a60-47b6-8a83-0f0460dd065c
		summarizeBy: sum
		sourceColumn: RegistrerteStudenter

		annotation SummarizationSetBy = Automatic

	column SPE60_Baseline_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: 4bd4b5c2-fa33-468c-a0da-0ac42b5fdbf3
		summarizeBy: sum
		sourceColumn: SPE60_Baseline_2025

		annotation SummarizationSetBy = Automatic

	column SPE60_Vekst_2025
		dataType: double
		formatString: #,##0.0
		lineageTag: f0a94dcf-877c-48ef-b8a7-3fee74122b39
		summarizeBy: sum
		sourceColumn: SPE60_Vekst_2025

		annotation SummarizationSetBy = Automatic

	column SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: 2d8eb9de-3ba7-4cc7-bac9-95076d114192
		summarizeBy: sum
		sourceColumn: SPE60

		annotation SummarizationSetBy = Automatic

	column KDKategori
		dataType: string
		lineageTag: efbe7f1a-a110-4654-9c4b-c017bc2fa1ab
		summarizeBy: none
		sourceColumn: KDKategori

		annotation SummarizationSetBy = Automatic

	column KDSats_NOK
		dataType: double
		formatString: #,##0
		lineageTag: a8ddc4d7-0435-4cb3-b6e0-708421774255
		summarizeBy: sum
		sourceColumn: KDSats_NOK

		annotation SummarizationSetBy = Automatic

	column KD_Marginal_Inntekt_2027
		dataType: double
		formatString: #,##0
		lineageTag: fb307857-06a3-4a1a-9be5-ac261f583478
		summarizeBy: sum
		sourceColumn: KD_Marginal_Inntekt_2027

		annotation SummarizationSetBy = Automatic

	column Studenter_pr_UF
		dataType: double
		formatString: 0.0
		lineageTag: eedc4943-5b6b-4ab1-8624-456518e2b781
		summarizeBy: average
		sourceColumn: Studenter_pr_UF

		annotation SummarizationSetBy = Automatic

	column StudenterPrUF
		dataType: double
		formatString: 0.0
		lineageTag: 8b5a2ca6-483c-4e65-a934-9f89e2439079
		summarizeBy: average
		sourceColumn: StudenterPrUF

		annotation SummarizationSetBy = Automatic

	partition FactStudents_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactStudents_2027.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StudentNokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Studieprogram", type text}, {"RegistrerteStudenter", Int64.Type}, {"SPE60_Baseline_2025", type number}, {"SPE60_Vekst_2025", type number}, {"SPE60", type number}, {"KDKategori", type text}, {"KDSats_NOK", type number}, {"KD_Marginal_Inntekt_2027", type number}, {"Studenter_pr_UF", type number}}),
				    #"Added StudenterPrUF" = Table.AddColumn(#"Changed Type", "StudenterPrUF", each [Studenter_pr_UF], type number)
				in
				    #"Added StudenterPrUF"

	annotation PBI_ResultType = Table

