table FactFTE
	lineageTag: 240c7586-506c-44ea-b0cb-56b9d0d2800d

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: bca42a20-4e64-4853-940c-b3b03afb1b5b
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: e2ca1cdb-3362-4af6-be46-d0c32da18b94
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Budsjettansvarsområde
		dataType: string
		lineageTag: e5281848-3568-44f6-9a44-ef4856fbe55c
		summarizeBy: none
		sourceColumn: Budsjettansvarsområde

		annotation SummarizationSetBy = Automatic

	column BudsjettansvarligLeder
		dataType: string
		lineageTag: 0f3bb677-3224-4df9-8373-244d9bd6ead3
		summarizeBy: none
		sourceColumn: BudsjettansvarligLeder

		annotation SummarizationSetBy = Automatic

	column Stillingstype
		dataType: string
		lineageTag: dce580da-c0cf-4cbf-8d25-1173ce4634bb
		summarizeBy: none
		sourceColumn: Stillingstype

		annotation SummarizationSetBy = Automatic

	column Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: 06ee27ec-8e22-45cc-b3a3-309441e41f37
		summarizeBy: sum
		sourceColumn: Aarsverk

		annotation SummarizationSetBy = Automatic

	column Budsjettert_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: 94d63457-8340-41fb-b8e5-b01738bf38f6
		summarizeBy: sum
		sourceColumn: Budsjettert_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Aarsverk_UF
		dataType: double
		formatString: #,##0.0
		lineageTag: c88fc615-be4f-468b-acdf-f4e75bd96f87
		summarizeBy: sum
		sourceColumn: Aarsverk_UF

		annotation SummarizationSetBy = Automatic

	column Aarsverk_TA
		dataType: double
		formatString: #,##0.0
		lineageTag: 9beadb61-25c7-4caf-a8a7-b5bffb40e423
		summarizeBy: sum
		sourceColumn: Aarsverk_TA

		annotation SummarizationSetBy = Automatic

	column Aarsverk_Totalt
		dataType: double
		formatString: #,##0.0
		lineageTag: 60e94b47-7142-4aa8-a87e-f7d0354edbc9
		summarizeBy: sum
		sourceColumn: Aarsverk_Totalt

		annotation SummarizationSetBy = Automatic

	column Vakans_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: f9c36fe6-8f78-4b0a-97cc-aceaefa52f44
		summarizeBy: sum
		sourceColumn: Vakans_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Antall_Ansatte
		dataType: int64
		formatString: 0
		lineageTag: d38d01e6-b2ce-49d7-8b73-de5194c6f453
		summarizeBy: sum
		sourceColumn: Antall_Ansatte

		annotation SummarizationSetBy = Automatic

	column Vakansgrad_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: 3c096092-f304-4165-93d7-18bbf0bc442f
		summarizeBy: average
		sourceColumn: Vakansgrad_Pct

		annotation SummarizationSetBy = Automatic

	partition FactFTE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactFTE.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Budsjettansvarsområde", type text}, {"BudsjettansvarligLeder", type text}, {"Aarsverk_UF", type number}, {"Aarsverk_TA", type number}, {"Aarsverk_Totalt", type number}, {"Budsjettert_Aarsverk", type number}, {"Vakans_Aarsverk", type number}, {"Antall_Ansatte", Int64.Type}, {"Vakansgrad_Pct", type number}}),
				    #"Added UF Ratio" = Table.AddColumn(#"Changed Type", "UF_Ratio", each if [Aarsverk_Totalt] = 0 then 0.5 else [Aarsverk_UF] / [Aarsverk_Totalt], type number),
				    #"UF Table" = Table.AddColumn(Table.AddColumn(Table.AddColumn(#"Added UF Ratio", "Stillingstype", each "UF", type text), "Aarsverk", each [Aarsverk_UF], type number), "Budsjett_ÅV", each [Budsjettert_Aarsverk] * [UF_Ratio], type number),
				    #"TA Table" = Table.AddColumn(Table.AddColumn(Table.AddColumn(#"Added UF Ratio", "Stillingstype", each "TA", type text), "Aarsverk", each [Aarsverk_TA], type number), "Budsjett_ÅV", each [Budsjettert_Aarsverk] * (1 - [UF_Ratio]), type number),
				    #"Combined" = Table.Combine({#"UF Table", #"TA Table"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Combined", {"UF_Ratio", "Budsjettert_Aarsverk"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns", {{"Budsjett_ÅV", "Budsjettert_Aarsverk"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

