table FactFTE_2027
	lineageTag: 77b74a02-57c3-4bf1-8d7d-4856c5b07e0e

	column FTENokkel
		dataType: string
		lineageTag: 0e689bf5-be16-4f81-9d07-5091731947c9
		summarizeBy: none
		sourceColumn: FTENokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 66f62b80-93b6-450b-af65-2d83b8eb874c
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: d58322b9-26fe-4b29-841f-3cc146279935
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Budsjettert_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: 1e64405c-6b52-4a7d-8069-c7c9911a738c
		summarizeBy: sum
		sourceColumn: Budsjettert_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Vakans_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: b5e1f5a6-410b-455e-8793-f88eaca90922
		summarizeBy: sum
		sourceColumn: Vakans_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Aarsverk_Totalt
		dataType: double
		formatString: #,##0.0
		lineageTag: 262a8cc1-7dc5-409f-aa4e-413d55231423
		summarizeBy: sum
		sourceColumn: Aarsverk_Totalt

		annotation SummarizationSetBy = Automatic

	column Aarsverk_UF
		dataType: double
		formatString: #,##0.0
		lineageTag: fa96f87e-93fa-48bd-a395-52a02a941547
		summarizeBy: sum
		sourceColumn: Aarsverk_UF

		annotation SummarizationSetBy = Automatic

	column Aarsverk_TA
		dataType: double
		formatString: #,##0.0
		lineageTag: ebb30c65-9467-4396-b907-ae307163e798
		summarizeBy: sum
		sourceColumn: Aarsverk_TA

		annotation SummarizationSetBy = Automatic

	column Antall_Ansatte
		dataType: int64
		formatString: 0
		lineageTag: 35e2c850-7c36-4dd5-b2a8-229d950a2de6
		summarizeBy: sum
		sourceColumn: Antall_Ansatte

		annotation SummarizationSetBy = Automatic

	column Maanedlig_Lonnskostnad
		dataType: double
		formatString: #,##0
		lineageTag: beb0d943-5853-4670-b4c6-0b721ddec90b
		summarizeBy: sum
		sourceColumn: Maanedlig_Lonnskostnad

		annotation SummarizationSetBy = Automatic

	column Lennsandel_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: d0b415ab-8009-40df-b1f9-3ba55a960ab5
		summarizeBy: average
		sourceColumn: Lennsandel_Pct

		annotation SummarizationSetBy = Automatic

	partition FactFTE_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactFTE_2027.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"FTENokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Budsjettert_Aarsverk", type number}, {"Vakans_Aarsverk", type number}, {"Aarsverk_Totalt", type number}, {"Aarsverk_UF", type number}, {"Aarsverk_TA", type number}, {"Antall_Ansatte", Int64.Type}, {"Maanedlig_Lonnskostnad", type number}, {"Lennsandel_Pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

