table FactAction_2027
	lineageTag: 64b63754-2c5e-4358-a6e2-2837cd3a5204

	column TiltakID
		dataType: string
		lineageTag: 754b0c3d-cd1d-4c0d-8195-7cea1f97fb29
		summarizeBy: none
		sourceColumn: TiltakID

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: a06be126-7860-41fe-ba63-17c6bbb0584a
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Tiltaksnavn
		dataType: string
		lineageTag: f66a0014-cfef-40b9-add9-35e13dcea610
		summarizeBy: none
		sourceColumn: Tiltaksnavn

		annotation SummarizationSetBy = Automatic

	column Kategori
		dataType: string
		lineageTag: dfcdbad1-4414-44d9-88d6-e68cd05138bc
		summarizeBy: none
		sourceColumn: Kategori

		annotation SummarizationSetBy = Automatic

	column Ansvarlig
		dataType: string
		lineageTag: 646fab46-8c16-425c-af30-d09d248c8645
		summarizeBy: none
		sourceColumn: Ansvarlig

		annotation SummarizationSetBy = Automatic

	column ForventetEffekt
		dataType: double
		formatString: #,##0
		lineageTag: e551ccb8-5b3e-4bca-8173-8f5e4277227b
		summarizeBy: sum
		sourceColumn: ForventetEffekt

		annotation SummarizationSetBy = Automatic

	column RealisertEffekt
		dataType: double
		formatString: #,##0
		lineageTag: c92e7fed-cff9-4f14-a691-851d6eb83ac8
		summarizeBy: sum
		sourceColumn: RealisertEffekt

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 297e7d62-164c-4e0c-8aa1-97c86889593c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Beskrivelse
		dataType: string
		lineageTag: 5b032846-4c0d-45a5-b341-c4a81f24d9a9
		summarizeBy: none
		sourceColumn: Beskrivelse

		annotation SummarizationSetBy = Automatic

	partition FactAction_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactAction_2027.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TiltakID", type text}, {"OrgKode", type text}, {"Tiltaksnavn", type text}, {"Kategori", type text}, {"Ansvarlig", type text}, {"ForventetEffekt", type number}, {"RealisertEffekt", type number}, {"Status", type text}, {"Beskrivelse", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

