table FactBudget_2027
	lineageTag: fdd73325-9ef8-4a8e-b2f3-bd306cde8e4d

	column BudsjettNokkel
		dataType: string
		lineageTag: 8da98b65-e169-49aa-8b0e-fbbcc214b4a6
		summarizeBy: none
		sourceColumn: BudsjettNokkel

		annotation SummarizationSetBy = Automatic

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 469423b3-843d-49bd-990c-b8c30f96ba35
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: string
		lineageTag: 228b165c-15e5-403c-abe8-18e0c5f1bb43
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 676e6737-e55e-458a-a47d-3c34f50081ce
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: ae7fd946-bf9d-4de4-95a1-928e5c77051d
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column BudsjettBelop
		dataType: double
		formatString: #,##0
		lineageTag: d810487b-134f-469b-998e-31b1d7ad3142
		summarizeBy: sum
		sourceColumn: BudsjettBelop

		annotation SummarizationSetBy = Automatic

	column Valuta
		dataType: string
		lineageTag: 0a4f3f7c-22ec-40f9-8ae9-acf59e6cb995
		summarizeBy: none
		sourceColumn: Valuta

		annotation SummarizationSetBy = Automatic

	column Kommentar
		dataType: string
		lineageTag: 05da4ece-995e-4e40-8bac-f516a7557193
		summarizeBy: none
		sourceColumn: Kommentar

		annotation SummarizationSetBy = Automatic

	partition FactBudget_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\HHU\FactBudget_2027.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BudsjettNokkel", type text}, {"DatoNokkel", Int64.Type}, {"OrgKode", type text}, {"Konto", Int64.Type}, {"VersjonKode", type text}, {"BudsjettBelop", type number}, {"Valuta", type text}, {"Kommentar", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

