table DimDate
	lineageTag: 83b9a365-7f14-4f0e-b603-727fff328e8f
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: aea30598-9e64-4633-a5d7-143671cf07ac
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		formatString: yyyy-MM-dd
		isKey
		lineageTag: db017b4b-2c33-489d-952f-bd88e14700d4
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 13801bfe-c830-463f-8082-791e6a92b42e
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: b1485a25-f1dd-43bb-8831-ebac09dd5891
		summarizeBy: none
		sourceColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		sortByColumn: MaanedNummer
		lineageTag: 61edfba2-98f1-40cf-b590-58b5955c4a4a
		summarizeBy: none
		sourceColumn: MaanedNavn

		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: 6714411a-29fc-4833-8a40-689bdd96b324
		summarizeBy: none
		sourceColumn: Kvartal

		annotation SummarizationSetBy = Automatic

	column StatusPr30Sep
		dataType: string
		lineageTag: 4cf1c428-2834-4c2b-bcce-b11244e5fdcb
		summarizeBy: none
		sourceColumn: StatusPr30Sep

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\DimDate.csv"),[Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Dato", type date}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavn", type text}, {"Kvartal", type text}, {"StatusPr30Sep", type text}})
			in
			    #"Changed Type"

	annotation PBI_ResultType = Table
