table DimOrganization
	lineageTag: 8f917836-e983-418d-88fb-8cc30a9ef67c

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: e7d76d5f-72d5-45ed-a1a0-28a54e3984a6
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Enhet
		dataType: string
		lineageTag: a6033af0-a21a-44f9-b750-5cc412192245
		summarizeBy: none
		sourceColumn: Enhet
		sortByColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Kortnavn
		dataType: string
		lineageTag: aebc8a1c-1851-4faa-8485-d627f319c204
		summarizeBy: none
		sourceColumn: Kortnavn
		sortByColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column OverordnetEnhet
		dataType: int64
		formatString: 0
		lineageTag: 882c31c4-7a5a-4c66-b332-0b1d3b13dc11
		summarizeBy: none
		sourceColumn: OverordnetEnhet

		annotation SummarizationSetBy = Automatic

	column Nivaa
		dataType: int64
		formatString: 0
		lineageTag: b0745156-edb6-4d13-88b2-f80e78262617
		summarizeBy: none
		sourceColumn: Nivaa

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: bc79131a-1f3f-44f5-b8bd-4335ab700073
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Leder_Tittel
		dataType: string
		lineageTag: 52a12359-0de1-43b4-8a30-4aff406f9687
		summarizeBy: none
		sourceColumn: Leder_Tittel

		annotation SummarizationSetBy = Automatic

	column Leder_Epost
		dataType: string
		lineageTag: 52a12360-0de1-43b4-8a30-4aff406f9688
		summarizeBy: none
		sourceColumn: Leder_Epost

		annotation SummarizationSetBy = Automatic

	partition DimOrganization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\DimOrganization.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", Int64.Type}, {"Enhet", type text}, {"Kortnavn", type text}, {"OverordnetEnhet", Int64.Type}, {"Nivaa", Int64.Type}, {"Type", type text}, {"Leder_Tittel", type text}, {"Leder_Epost", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
