table FactGL
	lineageTag: f31cae70-4cc8-43f5-8e33-23bcba6a6fed

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 8e892a39-40bf-4ec1-8741-258636536922
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 2e92ab8a-b1f8-40a1-8937-5b1ad857ae21
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 140a9051-78f3-4b78-b1f3-0b28ba61bf27
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: 5311fd98-4fac-40db-9a63-730ebea2f06e
		summarizeBy: none
		sourceColumn: Kontonavn

		annotation SummarizationSetBy = Automatic

	column Artstype
		dataType: string
		lineageTag: 970638ed-c2c0-430f-a753-f9f4093ec715
		summarizeBy: none
		sourceColumn: Artstype

		annotation SummarizationSetBy = Automatic

	column Kategori
		dataType: string
		lineageTag: da7c6cdf-fd27-42c7-8149-94185cf8bd09
		summarizeBy: none
		sourceColumn: Kategori

		annotation SummarizationSetBy = Automatic

	column Belop_MNOK
		dataType: double
		formatString: #,##0.000
		lineageTag: 05c193b9-3540-4f1a-b259-57d3215a93a8
		summarizeBy: sum
		sourceColumn: Belop_MNOK

		annotation SummarizationSetBy = Automatic

	column Belop_signert_MNOK
		dataType: double
		formatString: #,##0.000
		lineageTag: 537eb815-7876-43e9-946f-4e5eabfb942d
		summarizeBy: sum
		sourceColumn: Belop_signert_MNOK

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: 2245fca1-29ae-45be-a580-027298b173b7
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	partition FactGL = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactGL.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", Int64.Type}, {"Konto", Int64.Type}, {"Kontonavn", type text}, {"Artstype", type text}, {"Kategori", type text}, {"Belop_MNOK", type number}, {"Belop_signert_MNOK", type number}, {"VersjonKode", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

