table FactFTE
	lineageTag: 9cc8859c-7e24-47e6-ba1c-4fcd9018cc7b

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: b61a6caf-d35d-4bbb-b2ec-819d82a7b44b
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: fa96b859-f68c-474c-908e-4d35af40f377
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Aarsverk_UF
		dataType: double
		formatString: #,##0.0
		lineageTag: 80b6af10-556f-4556-acbf-019c405152d0
		summarizeBy: sum
		sourceColumn: Aarsverk_UF

		annotation SummarizationSetBy = Automatic

	column Aarsverk_TA
		dataType: double
		formatString: #,##0.0
		lineageTag: 3420f770-81a2-4769-8518-d67220c24e3a
		summarizeBy: sum
		sourceColumn: Aarsverk_TA

		annotation SummarizationSetBy = Automatic

	column Aarsverk_Faktisk
		dataType: double
		formatString: #,##0.0
		lineageTag: 986be88a-c60f-4f87-bca1-e6eaa32b9bef
		summarizeBy: sum
		sourceColumn: Aarsverk_Faktisk

		annotation SummarizationSetBy = Automatic

	column Aarsverk_Budsjett
		dataType: double
		formatString: #,##0.0
		lineageTag: abbbf583-7c06-440e-9a62-9bf17a38a0f5
		summarizeBy: sum
		sourceColumn: Aarsverk_Budsjett

		annotation SummarizationSetBy = Automatic

	column Antall_Ansatte
		dataType: int64
		formatString: 0
		lineageTag: bfb06786-19fb-4518-a3b4-b875a747cd69
		summarizeBy: sum
		sourceColumn: Antall_Ansatte

		annotation SummarizationSetBy = Automatic

	column Ubesatte_Vakanser
		dataType: double
		formatString: #,##0.0
		lineageTag: 8005ce6a-8d63-4c9d-ba1c-ad41b841394e
		summarizeBy: sum
		sourceColumn: Ubesatte_Vakanser

		annotation SummarizationSetBy = Automatic

	column Faglig_Andel_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: c6f7aafe-7875-496c-b698-b10693467ea7
		summarizeBy: average
		sourceColumn: Faglig_Andel_Pct

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: b3bd9344-e263-4010-a867-6dd3eb8e8055
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	partition FactFTE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactFTE.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", Int64.Type}, {"Aarsverk_UF", type number}, {"Aarsverk_TA", type number}, {"Aarsverk_Faktisk", type number}, {"Aarsverk_Budsjett", type number}, {"Antall_Ansatte", Int64.Type}, {"Ubesatte_Vakanser", type number}, {"Faglig_Andel_Pct", type number}, {"VersjonKode", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

