table FactBudget
	lineageTag: 74cffa98-b916-4324-b274-2e26f16b8e32

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 95525c26-8b96-40d0-949d-50a7eb6fa27b
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: fb2d1f49-6e5a-4a90-a247-098be4401f9d
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 04307525-d406-4cb8-ba27-46b38ebc2c4e
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: c3ee0a05-671a-45b4-ae25-baa5b5b054a3
		summarizeBy: none
		sourceColumn: Kontonavn

		annotation SummarizationSetBy = Automatic

	column Artstype
		dataType: string
		lineageTag: 3a994210-5520-4d1c-b61f-9be7923a0853
		summarizeBy: none
		sourceColumn: Artstype

		annotation SummarizationSetBy = Automatic

	column Kategori
		dataType: string
		lineageTag: 2efb1c85-1f12-4d34-b726-3e2aaa6d14d2
		summarizeBy: none
		sourceColumn: Kategori

		annotation SummarizationSetBy = Automatic

	column Budsjett_MNOK
		dataType: double
		formatString: #,##0.000
		lineageTag: c7471c76-6231-4013-ac3c-71c7bb38dc6a
		summarizeBy: sum
		sourceColumn: Budsjett_MNOK

		annotation SummarizationSetBy = Automatic

	column Budsjett_signert_MNOK
		dataType: double
		formatString: #,##0.000
		lineageTag: 1ca8c8e3-c35f-4a65-924c-7f37e7979ade
		summarizeBy: sum
		sourceColumn: Budsjett_signert_MNOK

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: 3267e064-b1e8-42f9-b34e-1b36cd1ba0de
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	partition FactBudget = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactBudget.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", Int64.Type}, {"Konto", Int64.Type}, {"Kontonavn", type text}, {"Artstype", type text}, {"Kategori", type text}, {"Budsjett_MNOK", type number}, {"Budsjett_signert_MNOK", type number}, {"VersjonKode", type text}})
			in
			    #"Changed Type"

	annotation PBI_ResultType = Table
