table DimForecastVersion
	lineageTag: 0e9d1bc2-5e52-4d70-be7d-c5776539fbc1

	column VersjonKode
		dataType: string
		lineageTag: b670fbb9-e9e9-42fe-87cb-e64f6679ed49
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column VersjonNavn
		dataType: string
		lineageTag: 0409a4ae-2166-46d1-8272-e7d1d5822d0e
		summarizeBy: none
		sourceColumn: VersjonNavn

		annotation SummarizationSetBy = Automatic

	column VersjonType
		dataType: string
		lineageTag: 2b72a2f6-6e3b-4211-84a5-584f4bc8c61a
		summarizeBy: none
		sourceColumn: VersjonType

		annotation SummarizationSetBy = Automatic

	column GjeldendeDato
		dataType: string
		lineageTag: 53845674-a518-4b36-92a1-6d1698b668cf
		summarizeBy: none
		sourceColumn: GjeldendeDato

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f9a9e4cf-583f-452e-b950-d3eb7d943b72
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimForecastVersion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\DimForecastVersion (1).csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"VersjonKode", type text}, {"VersjonNavn", type text}, {"VersjonType", type text}, {"GjeldendeDato", type text}, {"Status", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

