table FactAction_2027
	lineageTag: 853fe109-0a55-484d-9fec-a44fedbbf0d3

	column TiltakID
		dataType: string
		lineageTag: 0c5174d8-f637-49f9-a092-1fb5d34150db
		summarizeBy: none
		sourceColumn: TiltakID

		annotation SummarizationSetBy = Automatic

	column TiltakNavn
		dataType: string
		lineageTag: a813bda7-df09-4ce8-b2ad-9d5fd33f4dce
		summarizeBy: none
		sourceColumn: TiltakNavn

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: a919d829-c3e0-487d-a126-187e967d058a
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: 4233163a-f4c5-4373-bc8b-bbacd6d4c112
		summarizeBy: none
		sourceColumn: OrgNavn

		annotation SummarizationSetBy = Automatic

	column ForventetEffektMNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 8794d2ea-cbd5-4084-8f00-39cc7519b595
		summarizeBy: sum
		sourceColumn: ForventetEffektMNOK

		annotation SummarizationSetBy = Automatic

	column RealisertEffektMNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 0c2f7608-c1ae-4653-af2e-f75a14add9b0
		summarizeBy: sum
		sourceColumn: RealisertEffektMNOK

		annotation SummarizationSetBy = Automatic

	column Realiseringsgrad
		dataType: double
		formatString: 0.0 %
		lineageTag: 89397752-8420-4ecf-b6d4-3055787801ed
		summarizeBy: average
		sourceColumn: Realiseringsgrad

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 80bb717f-0b0b-4efa-8ee0-c8f6a4d7cd29
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column AnsvarligRolle
		dataType: string
		lineageTag: 019cf858-1852-4d01-8370-3c0df9d83ae4
		summarizeBy: none
		sourceColumn: AnsvarligRolle

		annotation SummarizationSetBy = Automatic

	column StartDato
		dataType: string
		lineageTag: 132ca839-2cc5-4438-88aa-bb7545ef4063
		summarizeBy: none
		sourceColumn: StartDato

		annotation SummarizationSetBy = Automatic

	column FristDato
		dataType: string
		lineageTag: 0b26cdb5-6765-4824-b919-0698feb86f41
		summarizeBy: none
		sourceColumn: FristDato

		annotation SummarizationSetBy = Automatic

	column Prioritet
		dataType: string
		lineageTag: 3a75e1f7-9c45-4096-8089-0efbaa3a9f87
		summarizeBy: none
		sourceColumn: Prioritet

		annotation SummarizationSetBy = Automatic

	partition FactAction_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\FactAction_2027.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TiltakID", type text}, {"TiltakNavn", type text}, {"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"ForventetEffektMNOK", type number}, {"RealisertEffektMNOK", type number}, {"Realiseringsgrad", type number}, {"Status", type text}, {"AnsvarligRolle", type text}, {"StartDato", type text}, {"FristDato", type text}, {"Prioritet", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

