table FactFTE_2027
	lineageTag: 60bf1844-5d25-436e-975a-f3821011d1a3

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 6f28e552-7a6f-48bc-bd06-1b00694094eb
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: ef18ddd9-8284-4073-8a61-343f8f33e229
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 6a7f95dd-e19f-42f2-a1f1-3d3ef32913f2
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: 8ee0f4ec-0f64-4224-a34b-e27428110c2b
		summarizeBy: none
		sourceColumn: OrgNavn

		annotation SummarizationSetBy = Automatic

	column Stillingstype
		dataType: string
		lineageTag: 5a567cbd-4c90-46eb-89d0-7006c4eb2d37
		summarizeBy: none
		sourceColumn: Stillingstype

		annotation SummarizationSetBy = Automatic

	column StillingsgruppeNavn
		dataType: string
		lineageTag: cd0b58ad-c12b-4f83-a118-66c63ec1d1c5
		summarizeBy: none
		sourceColumn: StillingsgruppeNavn

		annotation SummarizationSetBy = Automatic

	column Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: c6f77dfa-8ce2-4976-aaf1-2b2f3cb527ad
		summarizeBy: sum
		sourceColumn: Aarsverk

		annotation SummarizationSetBy = Automatic

	column AntallAnsatte
		dataType: int64
		formatString: 0
		lineageTag: dc311a44-4316-4419-8661-bd42eef4bb09
		summarizeBy: sum
		sourceColumn: AntallAnsatte

		annotation SummarizationSetBy = Automatic

	column Vakanser
		dataType: double
		formatString: #,##0.0
		lineageTag: 8934b0c7-5aa0-4b90-98dc-3e3043752ccf
		summarizeBy: sum
		sourceColumn: Vakanser

		annotation SummarizationSetBy = Automatic

	column SnittLonnNOK
		dataType: int64
		formatString: #,##0
		lineageTag: 1c408dd3-f0b7-44fa-b0e4-12f83e69946c
		summarizeBy: average
		sourceColumn: SnittLonnNOK

		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: 317a2d69-64bb-4f9b-a2d9-852054346f53
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	partition FactFTE_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\FactFTE_2027.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Aar", Int64.Type}, {"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"Stillingstype", type text}, {"StillingsgruppeNavn", type text}, {"Aarsverk", type number}, {"AntallAnsatte", Int64.Type}, {"Vakanser", type number}, {"SnittLonnNOK", Int64.Type}, {"VersjonKode", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

