table DimAccountHierarchy
	lineageTag: 130386d6-fb0e-42ad-b3f8-e58c52a0c4e7

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 2f725f39-f533-4b7d-a9ff-abf95f79db93
		summarizeBy: none
		sourceColumn: Konto
		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: 126b0475-ad5b-4770-a83e-2f69b0f10ba4
		summarizeBy: none
		sourceColumn: Kontonavn
		annotation SummarizationSetBy = Automatic

	column Nivaa1_Kontoklasse
		dataType: int64
		formatString: 0
		lineageTag: 4ce1d7d6-9697-415c-8031-6db4b6617074
		summarizeBy: none
		sourceColumn: Nivaa1_Kontoklasse
		annotation SummarizationSetBy = Automatic

	column Nivaa1_Navn
		dataType: string
		lineageTag: 770d3095-72dd-4bb1-a8f8-05a01612984f
		summarizeBy: none
		sourceColumn: Nivaa1_Navn
		annotation SummarizationSetBy = Automatic

	column Nivaa2_Kontogruppe
		dataType: int64
		formatString: 0
		lineageTag: a75aacde-8bac-4ec2-bb5b-8358c387ddb7
		summarizeBy: none
		sourceColumn: Nivaa2_Kontogruppe
		annotation SummarizationSetBy = Automatic

	column Nivaa2_Navn
		dataType: string
		lineageTag: f36dd7c6-922b-4206-bbd3-90e0caec3a0c
		summarizeBy: none
		sourceColumn: Nivaa2_Navn
		annotation SummarizationSetBy = Automatic

	column Nivaa3_Standardkonto
		dataType: int64
		formatString: 0
		lineageTag: 329e4e20-b82a-42b3-b972-f53f0d535d07
		summarizeBy: none
		sourceColumn: Nivaa3_Standardkonto
		annotation SummarizationSetBy = Automatic

	column Nivaa3_Navn
		dataType: string
		lineageTag: c53a3b0f-06a4-4616-939e-43efb6ce9c8c
		summarizeBy: none
		sourceColumn: Nivaa3_Navn
		annotation SummarizationSetBy = Automatic

	column Kontotype
		dataType: string
		lineageTag: cecd534b-a82b-4f22-9429-861436f3a493
		summarizeBy: none
		sourceColumn: Kontotype
		annotation SummarizationSetBy = Automatic

	column SRS_regnskapslinje
		dataType: string
		lineageTag: a0bb2c6c-d4b6-4de6-8fd6-103770a48623
		summarizeBy: none
		sourceColumn: SRS_regnskapslinje
		annotation SummarizationSetBy = Automatic

	partition DimAccountHierarchy = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\DimAccountHierarchy.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Konto", Int64.Type}, {"Kontonavn", type text}, {"Nivaa1_Kontoklasse", Int64.Type}, {"Nivaa1_Navn", type text}, {"Nivaa2_Kontogruppe", Int64.Type}, {"Nivaa2_Navn", type text}, {"Nivaa3_Standardkonto", Int64.Type}, {"Nivaa3_Navn", type text}, {"Kontotype", type text}, {"SRS_regnskapslinje", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
