table DimDate
	lineageTag: a691b507-4c4f-4700-853a-4df6b98d6f12
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 82b30786-9d25-4b85-b579-be8f28ad4bba
		summarizeBy: none
		sourceColumn: DatoNokkel
		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: 2ccaedad-d7c5-4ef8-ba70-75ccdfd87980
		summarizeBy: none
		sourceColumn: Dato
		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 377f21fa-6122-42e9-9a40-1e5662271cdb
		summarizeBy: none
		sourceColumn: Aar
		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: f924da41-8fd7-4fe2-8a5b-06c8317c5200
		summarizeBy: none
		sourceColumn: MaanedNummer
		annotation SummarizationSetBy = Automatic

	column MaanedNavnKort
		dataType: string
		lineageTag: a7a94477-3434-49ac-ade6-957d740f498e
		summarizeBy: none
		sourceColumn: MaanedNavnKort
		sortByColumn: MaanedNummer
		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		lineageTag: 7d1939fd-a37c-43ec-9628-e3ff9886e26a
		summarizeBy: none
		sourceColumn: MaanedNavn
		sortByColumn: MaanedNummer
		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: 11efbef8-7eb7-468c-8d56-b0dcb9e7b8de
		summarizeBy: none
		sourceColumn: Kvartal
		annotation SummarizationSetBy = Automatic

	column ErActualYTD
		dataType: boolean
		lineageTag: 8e5d0498-d435-4612-9469-ba5c325495d5
		summarizeBy: none
		sourceColumn: ErActualYTD
		annotation SummarizationSetBy = Automatic

	column PeriodeType
		dataType: string
		lineageTag: b6ee175f-1c5a-4018-8950-1e0095ef4741
		summarizeBy: none
		sourceColumn: PeriodeType
		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\DimDate.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Dato", type date}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavnKort", type text}, {"MaanedNavn", type text}, {"Kvartal", type text}, {"ErActualYTD", type logical}, {"PeriodeType", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
