table DimAccountHierarchy
	lineageTag: ba2293a5-5ea9-489f-a3a1-0eba7f75d53e

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 2c7e08db-936c-4be0-a19b-0f8542b7fe44
		summarizeBy: none
		sourceColumn: Konto

		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: ffb184c8-4602-40dd-bc3c-acbd4b009633
		summarizeBy: none
		sourceColumn: Kontonavn

		annotation SummarizationSetBy = Automatic

	column Nivaa1_Kontoklasse
		dataType: int64
		formatString: 0
		lineageTag: 776ba8d6-8385-4c6c-9999-d12a6daefb0d
		summarizeBy: none
		sourceColumn: Nivaa1_Kontoklasse

		annotation SummarizationSetBy = Automatic

	column Nivaa1_Navn
		dataType: string
		lineageTag: ea4b754c-ce14-44e6-a1d7-de7b648ce8ea
		summarizeBy: none
		sourceColumn: Nivaa1_Navn

		annotation SummarizationSetBy = Automatic

	column Nivaa2_Kontogruppe
		dataType: int64
		formatString: 0
		lineageTag: fb3f1e20-ea32-4484-bec1-576e5283b76c
		summarizeBy: none
		sourceColumn: Nivaa2_Kontogruppe

		annotation SummarizationSetBy = Automatic

	column Nivaa2_Navn
		dataType: string
		lineageTag: 706a0473-14c9-4ad8-8037-e6f974e7f2a2
		summarizeBy: none
		sourceColumn: Nivaa2_Navn

		annotation SummarizationSetBy = Automatic

	column Nivaa3_Standardkonto
		dataType: int64
		formatString: 0
		lineageTag: 9f238e72-9e69-4f88-9d28-e0dc96538204
		summarizeBy: none
		sourceColumn: Nivaa3_Standardkonto

		annotation SummarizationSetBy = Automatic

	column Nivaa3_Navn
		dataType: string
		lineageTag: dc8b0f74-e7de-4ec5-9000-97c476d3d7f6
		summarizeBy: none
		sourceColumn: Nivaa3_Navn

		annotation SummarizationSetBy = Automatic

	column Nivaa4_Underkonto
		dataType: int64
		formatString: 0
		lineageTag: 897b8e91-a173-4c91-b70a-f6a618cd64f9
		summarizeBy: none
		sourceColumn: Nivaa4_Underkonto

		annotation SummarizationSetBy = Automatic

	column Nivaa4_Navn
		dataType: string
		lineageTag: 3ff8a506-b867-420e-81d4-5b4d65ee1e9a
		summarizeBy: none
		sourceColumn: Nivaa4_Navn

		annotation SummarizationSetBy = Automatic

	column Kontotype
		dataType: string
		lineageTag: 89d04e79-3218-4975-b1a2-e8e7a94e7537
		summarizeBy: none
		sourceColumn: Kontotype

		annotation SummarizationSetBy = Automatic

	column SRS_regnskapslinje
		dataType: string
		lineageTag: 005f11f6-0c6e-49c1-a963-f039c8f2f235
		summarizeBy: none
		sourceColumn: SRS_regnskapslinje

		annotation SummarizationSetBy = Automatic

	partition DimAccountHierarchy = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\DimAccountHierarchy.csv"),[Delimiter=";", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Konto", Int64.Type}, {"Kontonavn", type text}, {"Nivaa1_Kontoklasse", Int64.Type}, {"Nivaa1_Navn", type text}, {"Nivaa2_Kontogruppe", Int64.Type}, {"Nivaa2_Navn", type text}, {"Nivaa3_Standardkonto", Int64.Type}, {"Nivaa3_Navn", type text}, {"Nivaa4_Underkonto", Int64.Type}, {"Nivaa4_Navn", type text}, {"Kontotype", type text}, {"SRS_regnskapslinje", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

