table DimDate
	lineageTag: 1526b4e0-d867-4df1-8e8b-c4a28d1910ad
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 95bf3f45-012f-490b-84be-919e4c7c9aa5
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: 0d352500-d7af-435d-be14-4224704e5ae8
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 2aa87c05-ccfc-4dc7-b892-55b352fab16f
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: 348e76a8-f1e9-4f09-a8be-fcc714066c66
		summarizeBy: none
		sourceColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		lineageTag: af612590-59e4-4411-bbbc-163c103dee20
		summarizeBy: none
		sourceColumn: MaanedNavn
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: c59763db-38ee-4c3b-8fb2-e37fb210d844
		summarizeBy: none
		sourceColumn: Kvartal

		annotation SummarizationSetBy = Automatic

	column StatusPr30Sep
		dataType: string
		lineageTag: c0b54b06-abaf-42a7-8ac5-46948e50888f
		summarizeBy: none
		sourceColumn: StatusPr30Sep

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\DimDate.csv"),[Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Dato", type date}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavn", type text}, {"Kvartal", type text}, {"StatusPr30Sep", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

