table DimForecastVersion
	lineageTag: 24bad1ed-85d8-496e-aa60-fce65da812a6

	column VersjonKode
		dataType: string
		lineageTag: b5f223b3-ec67-47ff-b3d9-5dc704eab0b5
		summarizeBy: none
		sourceColumn: VersjonKode

		annotation SummarizationSetBy = Automatic

	column VersjonNavn
		dataType: string
		lineageTag: 7c33c42d-d9de-4ba9-83a9-58ebd5930a9c
		summarizeBy: none
		sourceColumn: VersjonNavn

		annotation SummarizationSetBy = Automatic

	column Beskrivelse
		dataType: string
		lineageTag: 31ef7e6b-14b0-401d-bcea-3868ba963fbb
		summarizeBy: none
		sourceColumn: Beskrivelse

		annotation SummarizationSetBy = Automatic

	partition DimForecastVersion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\DimForecastVersion.csv"),[Delimiter=";", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"VersjonKode", type text}, {"VersjonNavn", type text}, {"Beskrivelse", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

