table FactFacultyKPI
	lineageTag: 668866d1-37db-42f1-aa49-9b3b352fc75e

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 39f48b5e-bb45-48cb-a09f-211b0b5a49b0
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Fakultet
		dataType: string
		lineageTag: b1008b57-c9ce-4ef3-9746-460df42399ce
		summarizeBy: none
		sourceColumn: Fakultet

		annotation SummarizationSetBy = Automatic

	column Statlig_Bevilgning_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 52e83c23-ce4b-4c16-8476-384ff76ceef5
		summarizeBy: sum
		sourceColumn: Statlig_Bevilgning_MNOK

		annotation SummarizationSetBy = Automatic

	column BOA_Andre_Inntekt_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 2eb3e993-6918-4253-bab8-4dea90d0691b
		summarizeBy: sum
		sourceColumn: BOA_Andre_Inntekt_MNOK

		annotation SummarizationSetBy = Automatic

	column Total_Inntekt_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: cbc827b8-ea11-49d0-b4e6-252d2047df4d
		summarizeBy: sum
		sourceColumn: Total_Inntekt_MNOK

		annotation SummarizationSetBy = Automatic

	column Lonnskostnader_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 95d24f0e-3dcf-4400-90da-7c56706f28c6
		summarizeBy: sum
		sourceColumn: Lonnskostnader_MNOK

		annotation SummarizationSetBy = Automatic

	column Driftskostnader_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 3fe65903-606c-4579-8431-267ae071b5f8
		summarizeBy: sum
		sourceColumn: Driftskostnader_MNOK

		annotation SummarizationSetBy = Automatic

	column Investeringer_Capex_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: bc954c37-3889-4a4f-b0e0-a65d94049f86
		summarizeBy: sum
		sourceColumn: Investeringer_Capex_MNOK

		annotation SummarizationSetBy = Automatic

	column Total_Kostnad_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 4333135a-6f7a-4495-97b5-ac770272f702
		summarizeBy: sum
		sourceColumn: Total_Kostnad_MNOK

		annotation SummarizationSetBy = Automatic

	column Netto_Resultat_MNOK
		dataType: double
		formatString: #,##0.00
		lineageTag: 972c6b71-3516-478b-b8fc-d50387c58873
		summarizeBy: sum
		sourceColumn: Netto_Resultat_MNOK

		annotation SummarizationSetBy = Automatic

	column Lonnsandel_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: 7a0db358-7e04-478b-b11f-475e8f1e8a54
		summarizeBy: average
		sourceColumn: Lonnsandel_Pct

		annotation SummarizationSetBy = Automatic

	column Aarsverk_UF
		dataType: double
		formatString: #,##0.0
		lineageTag: 14175f78-7f0a-4505-ab7f-7072dbba93ef
		summarizeBy: sum
		sourceColumn: Aarsverk_UF

		annotation SummarizationSetBy = Automatic

	column Aarsverk_TA
		dataType: double
		formatString: #,##0.0
		lineageTag: b5c63d66-6dea-4bcd-921c-fe2d0b452b0f
		summarizeBy: sum
		sourceColumn: Aarsverk_TA

		annotation SummarizationSetBy = Automatic

	column Total_Aarsverk
		dataType: double
		formatString: #,##0.0
		lineageTag: a5a72ebb-8d37-41dc-a932-b7fda2e048f0
		summarizeBy: sum
		sourceColumn: Total_Aarsverk

		annotation SummarizationSetBy = Automatic

	column Antall_Ansatte
		dataType: int64
		formatString: 0
		lineageTag: a9dda9a9-df22-40b1-90cb-30a38ff7b961
		summarizeBy: sum
		sourceColumn: Antall_Ansatte

		annotation SummarizationSetBy = Automatic

	column Antall_Studenter
		dataType: int64
		formatString: 0
		lineageTag: adf68cac-a2bb-417b-9f27-645c347181d6
		summarizeBy: sum
		sourceColumn: Antall_Studenter

		annotation SummarizationSetBy = Automatic

	column SPE60_Helarsstudenter
		dataType: double
		formatString: #,##0.0
		lineageTag: bb0e8505-a646-4681-acee-d834de732439
		summarizeBy: sum
		sourceColumn: SPE60_Helarsstudenter

		annotation SummarizationSetBy = Automatic

	column Studenter_Pr_Faglig_AV
		dataType: double
		formatString: #,##0.0
		lineageTag: 5114bef0-7e32-49f0-880f-a773b41b5a41
		summarizeBy: average
		sourceColumn: Studenter_Pr_Faglig_ÅV

		annotation SummarizationSetBy = Automatic

	column Kostnad_Pr_SPE60_NOK
		dataType: int64
		formatString: #,##0
		lineageTag: 87215f85-13f4-4bd7-8e6b-250285011af6
		summarizeBy: average
		sourceColumn: Kostnad_Pr_SPE60_NOK

		annotation SummarizationSetBy = Automatic

	column RAG_Status
		dataType: string
		lineageTag: 52d327d4-d0b4-4dfc-a23e-46678afaf876
		summarizeBy: none
		sourceColumn: RAG_Status

		annotation SummarizationSetBy = Automatic

	partition FactFacultyKPI = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactFacultyKPI.csv"),[Delimiter=";", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", Int64.Type}, {"Fakultet", type text}, {"Statlig_Bevilgning_MNOK", type number}, {"BOA_Andre_Inntekt_MNOK", type number}, {"Total_Inntekt_MNOK", type number}, {"Lonnskostnader_MNOK", type number}, {"Driftskostnader_MNOK", type number}, {"Investeringer_Capex_MNOK", type number}, {"Total_Kostnad_MNOK", type number}, {"Netto_Resultat_MNOK", type number}, {"Lonnsandel_Pct", type number}, {"Aarsverk_UF", type number}, {"Aarsverk_TA", type number}, {"Total_Aarsverk", type number}, {"Antall_Ansatte", Int64.Type}, {"Antall_Studenter", Int64.Type}, {"SPE60_Helarsstudenter", type number}, {"Studenter_Pr_Faglig_ÅV", type number}, {"Kostnad_Pr_SPE60_NOK", Int64.Type}, {"RAG_Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

