table FactStudents
	lineageTag: 904336ac-b83b-41ee-b023-198a022cf2ad

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: 217579c3-36dd-470d-a5f2-0d13b0c6fb3f
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: c1e7bf98-7b81-4c7e-99ca-5496c229e065
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Registrerte_Studenter
		dataType: int64
		formatString: 0
		lineageTag: f856c954-4ff4-4365-b59c-368bd0b5a366
		summarizeBy: sum
		sourceColumn: Registrerte_Studenter

		annotation SummarizationSetBy = Automatic

	column Avlagte_Studiepoeng_Totalt
		dataType: int64
		formatString: 0
		lineageTag: 87fd915c-734c-4cdb-8c69-7e0868c9ef8d
		summarizeBy: sum
		sourceColumn: Avlagte_Studiepoeng_Totalt

		annotation SummarizationSetBy = Automatic

	column SPE60_Helarsstudenter
		dataType: double
		formatString: #,##0.0
		lineageTag: e68663f8-97e3-4786-b2be-4a9753b35787
		summarizeBy: sum
		sourceColumn: SPE60_Helarsstudenter

		annotation SummarizationSetBy = Automatic

	column KD_Kategori1_SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: f0429def-cf5f-47f7-8b6d-393ef13ef715
		summarizeBy: sum
		sourceColumn: KD_Kategori1_SPE60

		annotation SummarizationSetBy = Automatic

	column KD_Kategori2_SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: 84f79bc8-5e96-4657-a197-6fce01baddab
		summarizeBy: sum
		sourceColumn: KD_Kategori2_SPE60

		annotation SummarizationSetBy = Automatic

	column KD_Kategori3_SPE60
		dataType: double
		formatString: #,##0.0
		lineageTag: a06288a5-c5a9-4648-8aed-44b6c550a969
		summarizeBy: sum
		sourceColumn: KD_Kategori3_SPE60

		annotation SummarizationSetBy = Automatic

	column Bestattandel_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: f86816ff-172a-4374-a3aa-3548f1668af9
		summarizeBy: average
		sourceColumn: Bestattandel_Pct

		annotation SummarizationSetBy = Automatic

	column Gjennomforing_Normert_Pct
		dataType: double
		formatString: 0.0%
		lineageTag: ccb1ed6d-85f0-4e82-bc4b-64c31de620c1
		summarizeBy: average
		sourceColumn: Gjennomforing_Normert_Pct

		annotation SummarizationSetBy = Automatic

	partition FactStudents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactStudents.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Aar", Int64.Type}, {"OrgKode", Int64.Type}, {"Registrerte_Studenter", Int64.Type}, {"Avlagte_Studiepoeng_Totalt", Int64.Type}, {"SPE60_Helarsstudenter", type number}, {"KD_Kategori1_SPE60", type number}, {"KD_Kategori2_SPE60", type number}, {"KD_Kategori3_SPE60", type number}, {"Bestattandel_Pct", type number}, {"Gjennomforing_Normert_Pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

