table FactEVM
	lineageTag: da63784d-8508-402a-aca0-92238405dc34

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 5989074b-1c2c-4014-9178-97884b943870
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: f6dff833-5322-4316-b92b-9e1867c5cef1
		summarizeBy: none
		sourceColumn: OrgKode

		annotation SummarizationSetBy = Automatic

	column Planned_Value_PV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 6dd6b1de-ba02-41b5-92fd-b7fd2021e171
		summarizeBy: sum
		sourceColumn: Planned_Value_PV_MNOK

		annotation SummarizationSetBy = Automatic

	column Earned_Value_EV_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 449f12bd-39ca-4cea-9e97-d33d75c14342
		summarizeBy: sum
		sourceColumn: Earned_Value_EV_MNOK

		annotation SummarizationSetBy = Automatic

	column Actual_Cost_AC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 4682d782-b0d6-46de-800a-13decf3ea620
		summarizeBy: sum
		sourceColumn: Actual_Cost_AC_MNOK

		annotation SummarizationSetBy = Automatic

	column Budget_At_Completion_BAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: be685606-a047-4af3-bd48-0899baa00412
		summarizeBy: sum
		sourceColumn: Budget_At_Completion_BAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_At_Completion_EAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: 047367e0-4d23-42e5-82b3-23ba2b9419ba
		summarizeBy: sum
		sourceColumn: Estimate_At_Completion_EAC_MNOK

		annotation SummarizationSetBy = Automatic

	column Estimate_To_Complete_ETC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: cdd2af82-b6c8-482f-b934-0a30a36d59a4
		summarizeBy: sum
		sourceColumn: Estimate_To_Complete_ETC_MNOK

		annotation SummarizationSetBy = Automatic

	column Cost_Performance_Index_CPI
		dataType: double
		formatString: 0.00
		lineageTag: ade5b7f2-f196-4086-ad9e-d5d332d8d106
		summarizeBy: average
		sourceColumn: Cost_Performance_Index_CPI

		annotation SummarizationSetBy = Automatic

	column Schedule_Performance_Index_SPI
		dataType: double
		formatString: 0.00
		lineageTag: 8aa4ec83-1cd5-499a-ba92-fbb565414d06
		summarizeBy: average
		sourceColumn: Schedule_Performance_Index_SPI

		annotation SummarizationSetBy = Automatic

	column Variance_At_Completion_VAC_MNOK
		dataType: double
		formatString: #,##0.0
		lineageTag: c8d3298c-1687-4605-85ea-83452cbf88fc
		summarizeBy: sum
		sourceColumn: Variance_At_Completion_VAC_MNOK

		annotation SummarizationSetBy = Automatic

	partition FactEVM = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\data\FactEVM.csv"),[Delimiter=";", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"OrgKode", Int64.Type}, {"Planned_Value_PV_MNOK", type number}, {"Earned_Value_EV_MNOK", type number}, {"Actual_Cost_AC_MNOK", type number}, {"Budget_At_Completion_BAC_MNOK", type number}, {"Estimate_At_Completion_EAC_MNOK", type number}, {"Estimate_To_Complete_ETC_MNOK", type number}, {"Cost_Performance_Index_CPI", type number}, {"Schedule_Performance_Index_SPI", type number}, {"Variance_At_Completion_VAC_MNOK", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

