table DimDate_2027
	lineageTag: 5b95878a-ab15-4e78-afcd-15756b5c7feb
	dataCategory: Time

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: 9ac8b995-7679-4ea0-ab21-222315872394
		summarizeBy: none
		sourceColumn: DatoNokkel

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: e6e71fa5-82ae-4f73-9509-e31b8b458948
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: b6830e06-df1e-4f25-9305-281aa89600e3
		summarizeBy: none
		sourceColumn: Aar

		annotation SummarizationSetBy = Automatic

	column MaanedNummer
		dataType: int64
		formatString: 0
		lineageTag: 5aca4123-0f72-41f3-9b93-ad6cb2517b07
		summarizeBy: none
		sourceColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavn
		dataType: string
		lineageTag: f5da5958-ced1-4429-be62-94a868050f3b
		summarizeBy: none
		sourceColumn: MaanedNavn
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column MaanedNavnKort
		dataType: string
		lineageTag: c7a94099-0a6e-437d-9284-22882a1f1648
		summarizeBy: none
		sourceColumn: MaanedNavnKort
		sortByColumn: MaanedNummer

		annotation SummarizationSetBy = Automatic

	column Kvartal
		dataType: string
		lineageTag: 160def5d-4f7d-4712-99c4-6d57bd993e39
		summarizeBy: none
		sourceColumn: Kvartal

		annotation SummarizationSetBy = Automatic

	column AarMaaned
		dataType: string
		lineageTag: 21769651-7ccd-4787-835f-c98299d6f63b
		summarizeBy: none
		sourceColumn: AarMaaned

		annotation SummarizationSetBy = Automatic

	column ErActualYTD
		dataType: boolean
		lineageTag: c836da8e-38f4-4b45-9b77-7cafce5a6eca
		summarizeBy: none
		sourceColumn: ErActualYTD

		annotation SummarizationSetBy = Automatic

	partition DimDate_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\DimDate_2027.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Dato", type date}, {"Aar", Int64.Type}, {"MaanedNummer", Int64.Type}, {"MaanedNavn", type text}, {"MaanedNavnKort", type text}, {"Kvartal", type text}, {"AarMaaned", type text}, {"ErActualYTD", type logical}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

