table DimOrganization
	lineageTag: 92293f1f-90db-4a8d-b85e-133b74ad5cb3

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: accad2b8-e5b1-4755-9263-b482d8988339
		summarizeBy: none
		sourceColumn: OrgKode
		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: 9b70e503-1a32-402e-a815-a1eaad376585
		summarizeBy: none
		sourceColumn: OrgNavn
		annotation SummarizationSetBy = Automatic

	column OrgNivaa
		dataType: string
		lineageTag: 8b5fef2a-7748-480c-9569-a3d37d4e0f91
		summarizeBy: none
		sourceColumn: OrgNivaa
		annotation SummarizationSetBy = Automatic

	column Fakultetsnavn
		dataType: string
		lineageTag: 7ca0c0e8-933a-4779-947a-884ae497b882
		summarizeBy: none
		sourceColumn: Fakultetsnavn
		annotation SummarizationSetBy = Automatic

	column Virksomhetstype
		dataType: string
		lineageTag: c2170867-03ba-46a7-9e75-6f5785a93e64
		summarizeBy: none
		sourceColumn: Virksomhetstype
		annotation SummarizationSetBy = Automatic

	column Lokalitet
		dataType: string
		lineageTag: f8e7961f-02f7-4032-a406-606b0d97c895
		summarizeBy: none
		sourceColumn: Lokalitet
		annotation SummarizationSetBy = Automatic

	partition DimOrganization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\DimOrganization (1).csv"),[Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"OrgNivaa", type text}, {"Fakultetsnavn", type text}, {"Virksomhetstype", type text}, {"Lokalitet", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
