table DimOrganization
	lineageTag: d07bbf07-2138-4404-9eff-ab149d718a75

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 3159f248-8280-4b59-b555-16ca8156826f
		summarizeBy: none
		sourceColumn: OrgKode
		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: 6e219b5b-72b0-4895-b1d7-53d09283ae78
		summarizeBy: none
		sourceColumn: OrgNavn
		annotation SummarizationSetBy = Automatic

	column OrgNivaa
		dataType: string
		lineageTag: cf0eb669-9ddc-4ef8-afd9-27db9460a38a
		summarizeBy: none
		sourceColumn: OrgNivaa
		annotation SummarizationSetBy = Automatic

	column Fakultetsnavn
		dataType: string
		lineageTag: fad20f50-65f5-40fd-afac-cbc139db5556
		summarizeBy: none
		sourceColumn: Fakultetsnavn
		annotation SummarizationSetBy = Automatic

	column Virksomhetstype
		dataType: string
		lineageTag: 50b25e4a-9db0-4e80-9a40-57c6f3b5810c
		summarizeBy: none
		sourceColumn: Virksomhetstype
		annotation SummarizationSetBy = Automatic

	column Lokalitet
		dataType: string
		lineageTag: 1e6f9d1b-eb31-421b-881d-7880dd22d8f6
		summarizeBy: none
		sourceColumn: Lokalitet
		annotation SummarizationSetBy = Automatic

	hierarchy 'Organisasjonshierarki'
		lineageTag: 56eda275-6c94-4034-a976-f8922d7de2fa

		level Fakultet
			lineageTag: e19dc151-4712-49cf-87b9-e451d136f12b
			column: Fakultetsnavn

		level Enhet
			lineageTag: a33ea2ce-7e5f-4f85-a82e-21d2d53cf104
			column: OrgNavn

	partition DimOrganization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\DimOrganization (1).csv"),[Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"OrgNivaa", type text}, {"Fakultetsnavn", type text}, {"Virksomhetstype", type text}, {"Lokalitet", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
