table FactStudents_2027
	lineageTag: d16bbd03-5ac4-46f6-962e-fb3711dccf02

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 9892e663-8a1a-4c6c-a922-c48d0f399549
		summarizeBy: none
		sourceColumn: OrgKode
		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: 1d513420-c9df-4860-b707-f26d37d53951
		summarizeBy: none
		sourceColumn: OrgNavn
		annotation SummarizationSetBy = Automatic

	column StudieprogramNavn
		dataType: string
		lineageTag: b887f589-29fe-4993-b42e-8aa718e81abc
		summarizeBy: none
		sourceColumn: StudieprogramNavn
		annotation SummarizationSetBy = Automatic

	column KDKategori
		dataType: string
		lineageTag: 5bbbf344-8b35-4700-9ad8-7b2b92adde61
		summarizeBy: none
		sourceColumn: KDKategori
		annotation SummarizationSetBy = Automatic

	column RegistrerteStudenter
		dataType: int64
		formatString: #,##0
		lineageTag: 02d299d7-68af-405e-a1e3-5b529c6db696
		summarizeBy: sum
		sourceColumn: RegistrerteStudenter
		annotation SummarizationSetBy = Automatic

	column SPE60_2025_Lag
		dataType: double
		formatString: #,##0.0
		lineageTag: eba88519-f259-4308-972a-4a53350f4d5d
		summarizeBy: sum
		sourceColumn: SPE60_2025_Lag
		annotation SummarizationSetBy = Automatic

	column SPE60_2027_Target
		dataType: double
		formatString: #,##0.0
		lineageTag: 86f5633b-2814-4cdc-b960-5c165f909e65
		summarizeBy: sum
		sourceColumn: SPE60_2027_Target
		annotation SummarizationSetBy = Automatic

	column KDInntektBeregnetNOK
		dataType: double
		formatString: #,##0
		lineageTag: b6cc20cc-786c-48e3-ba85-b004e1753c31
		summarizeBy: sum
		sourceColumn: KDInntektBeregnetNOK
		annotation SummarizationSetBy = Automatic

	column StudenterPrUF
		dataType: double
		formatString: 0.0
		lineageTag: 85f6e597-224f-4150-9543-72050f6c0fc8
		summarizeBy: average
		sourceColumn: StudenterPrUF
		annotation SummarizationSetBy = Automatic

	partition FactStudents_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\FactStudents_2027.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"StudieprogramNavn", type text}, {"KDKategori", type text}, {"RegistrerteStudenter", Int64.Type}, {"SPE60_2025_Lag", type number}, {"SPE60_2027_Target", type number}, {"KDInntektBeregnetNOK", type number}, {"StudenterPrUF", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
