table FactBudget_2027
	lineageTag: 964c7776-5998-4680-a264-d7e2b240635c

	column DatoNokkel
		dataType: int64
		formatString: 0
		lineageTag: d24d4bd4-ea83-432d-8919-5eca1e9cc71a
		summarizeBy: none
		sourceColumn: DatoNokkel
		annotation SummarizationSetBy = Automatic

	column Aar
		dataType: int64
		formatString: 0
		lineageTag: e16c0d49-d01f-4b67-843b-9f7aa4afe288
		summarizeBy: none
		sourceColumn: Aar
		annotation SummarizationSetBy = Automatic

	column AarMaaned
		dataType: string
		lineageTag: b51659a1-f065-4c37-b0f5-722b6f5f05a6
		summarizeBy: none
		sourceColumn: AarMaaned
		annotation SummarizationSetBy = Automatic

	column OrgKode
		dataType: int64
		formatString: 0
		lineageTag: 52aba47f-3c3c-4c2b-aaac-a585fdf65376
		summarizeBy: none
		sourceColumn: OrgKode
		annotation SummarizationSetBy = Automatic

	column OrgNavn
		dataType: string
		lineageTag: e5c35ce4-92ff-4b1b-ae81-0767e9ec5020
		summarizeBy: none
		sourceColumn: OrgNavn
		annotation SummarizationSetBy = Automatic

	column Konto
		dataType: int64
		formatString: 0
		lineageTag: 31f8c8d1-fcb2-4a38-bf94-81b54329afb4
		summarizeBy: none
		sourceColumn: Konto
		annotation SummarizationSetBy = Automatic

	column Kontonavn
		dataType: string
		lineageTag: 220bd694-1ed6-4bb7-90c1-8f6241be5aeb
		summarizeBy: none
		sourceColumn: Kontonavn
		annotation SummarizationSetBy = Automatic

	column VersjonKode
		dataType: string
		lineageTag: a44ddf42-18bb-4571-b3eb-5e5a384e5e9c
		summarizeBy: none
		sourceColumn: VersjonKode
		annotation SummarizationSetBy = Automatic

	column BudsjettBelop
		dataType: double
		formatString: #,##0.0
		lineageTag: ff151d85-212a-4147-887e-606593755132
		summarizeBy: sum
		sourceColumn: BudsjettBelop
		annotation SummarizationSetBy = Automatic

	column Kilde
		dataType: string
		lineageTag: 656f7f9d-98a2-4166-856d-ed273dca20c7
		summarizeBy: none
		sourceColumn: Kilde
		annotation SummarizationSetBy = Automatic

	partition FactBudget_2027 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\frank\Desktop\UIA2\Handelshøyskolen\Budsjett2027\FactBudget_2027.csv"),[Delimiter=";", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Aar", Int64.Type}, {"AarMaaned", type text}, {"OrgKode", Int64.Type}, {"OrgNavn", type text}, {"Konto", Int64.Type}, {"Kontonavn", type text}, {"VersjonKode", type text}, {"BudsjettBelop", type number}, {"Kilde", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
